name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Archive
        uses: thedoctor0/zip-release@master
        with:
          filename: "BCRYExporter.zip"
          directory: ./io_bcry_exporter
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "BCRYExporter.zip"
          token: ${{ secrets.GITHUB_TOKEN }}