name: Release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload release
        uses: thedoctor0/zip-release@master
        with:
          filename: "BCRYExporter.zip"
          directory: ./io_bcry_exporter